#!/usr/bin/env sh
export LC_ALL=EN_US.UTF-8
if [[ -z "$SSH_TTY" ]]; then
  unset TERM
else
  export TERM=xterm
fi
if [[ "OS400" == $(uname) ]]; then
  : ${JAVA_HOME=/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit}
  exec $JAVA_HOME/bin/java -cp $(dirname $0)/nestedjarsearch.jar com.github.theprez.JarSearch "$@"
else
  exec java -cp $(dirname $0)/nestedjarsearch.jar com.github.theprez.JarSearch "$@"
fi
